name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: ./   # carpeta donde está angular.json

      - name: Build (prod)
        run: npm run build -- --configuration=production
        working-directory: ./

      - name: Copy SWA config to output
        run: cp staticwebapp.config.json dist/Opticas/browser/ || true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          skip_app_build: true
          app_location: "dist/Opticas/browser"   # <-- aquí sí está index.html
