name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: ./          # <-- carpeta donde está tu angular.json

      - name: Build (prod)
        run: npm run build -- --configuration=production
        working-directory: ./

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}     # opcional, útil para PRs
          action: upload                              # <-- clave para evitar tu error
          skip_app_build: true                        # ya construimos arriba
          app_location: "./"                          # donde está angular.json
          output_location: "dist/Opticas"             # salida del build (por compat)
          app_artifact_location: "dist/Opticas"       # carpeta a subir cuando skip_app_build
